/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, NativeEventEmitter, NativeModules, TouchableOpacity } from 'react-native';
import CBBluetoothpx from 'react-native-bluetoothpx';

export default class App extends Component {
  state = {
    printerState: "",
    devices: []
  };

  getDevices = () => {
    CBBluetoothpx.getBluetoothList((e) => {
      this.setState({
        devices: e.devices
      })
    });
  }

  componentDidMount() {

    console.log("componentDidMount")

    this.getDevices()

    const eventEmitter = new NativeEventEmitter(CBBluetoothpx);
    eventEmitter.addListener("printerStateChange", (e) => {
      this.setState({ printerState: e })
    })

  }

  connect = (device) => () => {
    CBBluetoothpx.connect(device.deviceAddress)
  }

  testPrint = () => {

   try {
    CBBluetoothpx.addText("PrinterTest", 1,0);
    CBBluetoothpx.flushText();
    CBBluetoothpx.addText("TouchableOpacity", 1,0);
    CBBluetoothpx.flushText();
    CBBluetoothpx.addText("ทัสเซเบิลโอบาซิตี้", 1,0);
    CBBluetoothpx.flushText();
    CBBluetoothpx.addFeedLine(1);
    CBBluetoothpx.addBarcode("01209457");
    CBBluetoothpx.flushText();
    CBBluetoothpx.addQRcode("http://www.xxxxxxxxx.com/");
    CBBluetoothpx.flushText();
 
    CBBluetoothpx.sendData()
   } catch (error) {
     
   }
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>PrinterTest</Text>
        <TouchableOpacity onPress={this.testPrint} style={{ backgroundColor: 'red', padding: 10, borderRadius: 10 }}>
          <Text>testPrint</Text>
        </TouchableOpacity>
        <Text>{JSON.stringify(this.state.printerState)}</Text>
        {this.state.devices.map((b) => {
          return (
            <TouchableOpacity key={`${b.deviceAddress}`} onPress={this.connect(b)} style={{ backgroundColor: 'red', padding: 10, borderRadius: 10 }}>
              <Text> {`${b.deviceName} : ${b.deviceAddress}`}</Text>
            </TouchableOpacity>
          )
        })}
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
